In [1]:
import pandas as pd
from datetime import date
import json

In [2]:
# read in ppe info for past updates
ppe_crunched = pd.read_csv("resources/weeks_01-39.csv")

# read in ppe info from previous ppe_cruncher_updates notebook
weekly_df = pd.read_csv("resources/weekly_df_backup_03_22_2021.csv")

## Combining Data Sets.

In [3]:
# create new week number column in weekly_df, for continuous indexing
weekly_df.rename(columns = {'week number':'old week number'}, inplace = True)

# create new column with new week numbers, drop old column
weekly_df["week number"] = weekly_df["old week number"] + 38
weekly_df.drop(['old week number'], axis = 1)

,county,week,Examination Gloves,Viral Testing Media,Swabs,Other / None of the above,Cleaning Supplies,Surgical or Examination Gowns,Wipes,Shoe Covers,...,Goggles,Lab Kit,Body Bags,Personnel,Beds/Cots,Ventilators,Lab Platform,Fit Testing Supplies,Bedding Accessories,week number
0,['Los Angeles'],2021-02-27 to 2021-03-05,[411543000.0],[7616182.0],[11036550.0],[1773730.0],[170800.0],[88477892.0],[27608472.0],[359100.0],...,[480600.0],[0.0],[33740.0],[24894.0],[1834.0],[7392.0],[0.0],[266.0],[0.0],39
1,['Solano'],2021-02-27 to 2021-03-05,[17705520.0],[411978.0],[693700.0],[100457.0],[0.0],[678496.0],[40320.0],[5250.0],...,[70700.0],[45500.0],[0.0],[126.0],[0.0],[0.0],[0.0],[35.0],[0.0],39
2,['Fresno'],2021-02-27 to 2021-03-05,[34865040.0],[801500.0],[1052800.0],[491519.0],[0.0],[1321810.0],[1820000.0],[241150.0],...,[79800.0],[0.0],[0.0],[2541.0],[0.0],[28.0],[0.0],[861.0],[0.0],39
3,['Mendocino'],2021-02-27 to 2021-03-05,[3920000.0],[122241.0],[207200.0],[80150.0],[224000.0],[507710.0],[266560.0],[0.0],...,[21000.0],[0.0],[0.0],[84.0],[301.0],[21.0],[0.0],[0.0],[0.0],39
4,['Trinity'],2021-02-27 to 2021-03-05,[1750000.0],[20650.0],[35707.0],[18200.0],[0.0],[89978.0],[25200.0],[0.0],...,[0.0],[0.0],[0.0],[56.0],[0.0],[0.0],[0.0],[0.0],[0.0],39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,['Merced'],2021-03-13 to 2021-03-19,[],[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],[],[],42
228,['Glenn'],2021-03-13 to 2021-03-19,[],[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],[],[],42
229,['Plumas'],2021-03-13 to 2021-03-19,[],[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],[],[],42
230,['Sierra'],2021-03-13 to 2021-03-19,[],[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],[],[],42
231,['Alpine'],2021-03-13 to 2021-03-19,[],[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],[],[],42

In [4]:
print(weekly_df['week number'].unique())

[39 40 41 42]

In [5]:
# drop the last week in ppe_crunched with no elements to utilize
ppe_crunched = ppe_crunched.loc[ppe_crunched['week number'] < 39]
print(ppe_crunched['week number'].unique())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38]

In [6]:
# append new dataframes to previous ppe info, for a complete dataset
new_df = ppe_crunched.append(weekly_df)

In [7]:
print(new_df['week number'].unique())
new_df

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42]

,county,week,week number,Face Shields (Disposable),Surgical Masks,Cloth Masks,Surgical or Examination Gowns,Examination Gloves,N-95 Respirators,Hand Sanitizers,...,Beds/Cots,Body Bags,Lab Kit,Ventilators,Personnel,Sample Collecting Kits,Lab Platform,Bedding Accessories,Fit Testing Supplies,old week number
0,['Kern'],2020-06-10 to 2020-06-16,1,[1656500.0],[2282000.0],[3673500.0],[2143190.0],[1161000.0],[3658718.0],[5707127.0],...,[0.0],[0.0],[0.0],[0.0],[539.0],[0.0],[0.0],[0.0],[0.0],NaN
1,['Mariposa'],2020-06-10 to 2020-06-16,1,[840.0],[568000.0],[0.0],[11592.0],[0.0],[1680.0],[32928.0],...,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],NaN
2,['Merced'],2020-06-10 to 2020-06-16,1,[63480.0],[2894000.0],[19000.0],[802550.0],[2072000.0],[246960.0],[1890.0],...,[0.0],[2800.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],NaN
3,['Mono'],2020-06-10 to 2020-06-16,1,[5900.0],[461000.0],[20500.0],[19558.0],[381500.0],[308420.0],[30622.0],...,[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],[0.0],NaN
4,['Napa'],2020-06-10 to 2020-06-16,1,[78344.0],[774000.0],[612000.0],[172480.0],[660000.0],[820628.0],[1019012.0],...,[0.0],[0.0],[0.0],[0.0],[0.0],[36400.0],[0.0],[0.0],[0.0],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,['Merced'],2021-03-13 to 2021-03-19,42,[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],[],[],4.0
228,['Glenn'],2021-03-13 to 2021-03-19,42,[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],[],[],4.0
229,['Plumas'],2021-03-13 to 2021-03-19,42,[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],[],[],4.0
230,['Sierra'],2021-03-13 to 2021-03-19,42,[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],[],[],4.0
231,['Alpine'],2021-03-13 to 2021-03-19,42,[],[],[],[],[],[],[],...,[],[],[],[],[],[],[],[],[],4.0

In [8]:
# redundant backup
new_df.to_csv(f"resources/weeks_01-42.csv", index=False, header=True)

## Clean up, formatting.

In [9]:
# fix county with string replace
new_df["county"] = new_df["county"].str.replace("[", "")
new_df["county"] = new_df["county"].str.replace("]", "")
new_df["county"] = new_df["county"].str.replace("'", "")
print(new_df["county"].unique())

['Kern' 'Mariposa' 'Merced' 'Mono' 'Napa' 'Santa Barbara' 'Sutter' 'Modoc'
 'Del Norte' 'Placer' 'Trinity' 'Sacramento' 'San Benito' 'Yuba' 'Ventura'
 'Sonoma' 'San Joaquin' 'Alameda' 'Monterey' 'Solano' 'San Francisco'
 'Stanislaus' 'Orange' 'Nevada' 'San Luis Obispo' 'Lassen' 'Imperial'
 'San Bernardino' 'Santa Clara' 'San Diego' 'Humboldt' 'Tulare'
 'Los Angeles' 'Mendocino' 'Kings' 'Madera' 'Contra Costa' 'Siskiyou'
 'Inyo' 'San Mateo' 'Calaveras' 'Santa Cruz' 'Yolo' 'Marin' 'Riverside'
 'Colusa' 'Shasta' 'Alpine' 'Lake' 'Fresno' 'Amador' 'Tuolumne'
 'El Dorado' 'Glenn' 'Tehama' 'Butte' 'Plumas' 'Sierra']

In [10]:
# create list of product families
product_list = ['Face Shields (Disposable)', 'Surgical Masks', 'Cloth Masks', 'Surgical or Examination Gowns',
            'Examination Gloves', 'N-95 Respirators', 'Hand Sanitizers', 'Wipes', 'Other / None of the above',
            'Cleaning Supplies', 'Swabs', 'Viral Testing Media', 'Pharmaceuticals', 'Shoe Covers', 'Test Kits',
            'KN95 Respirators', 'Coveralls (Hospitals or EMS)', 'Medical Equipment', 'Goggles', 'Lab Supplies',
            'Beds/Cots', 'Body Bags', 'Lab Kit', 'Ventilators', 'Personnel', 'Sample Collecting Kits', 'Lab Platform',
            'Bedding Accessories', 'Fit Testing Supplies']
print(product_list)
print(len(product_list))

['Face Shields (Disposable)', 'Surgical Masks', 'Cloth Masks', 'Surgical or Examination Gowns', 'Examination Gloves', 'N-95 Respirators', 'Hand Sanitizers', 'Wipes', 'Other / None of the above', 'Cleaning Supplies', 'Swabs', 'Viral Testing Media', 'Pharmaceuticals', 'Shoe Covers', 'Test Kits', 'KN95 Respirators', 'Coveralls (Hospitals or EMS)', 'Medical Equipment', 'Goggles', 'Lab Supplies', 'Beds/Cots', 'Body Bags', 'Lab Kit', 'Ventilators', 'Personnel', 'Sample Collecting Kits', 'Lab Platform', 'Bedding Accessories', 'Fit Testing Supplies']
29

In [11]:
# iterate through product list and string replace each remaining column left to clean
for product in product_list:
    new_df[product] = new_df[product].str.replace("[", "")
    new_df[product] = new_df[product].str.replace("]", "")

In [12]:
# replace nan values in dataframe with zeroes, for entire dataframe
new_df = new_df.fillna(0)

In [13]:
# drop the last week in ppe_crunched with no elements to utilize
new_df = new_df.loc[new_df['week number'] < 42]

In [14]:
# columns with brackets are strings
new_df

,county,week,week number,Face Shields (Disposable),Surgical Masks,Cloth Masks,Surgical or Examination Gowns,Examination Gloves,N-95 Respirators,Hand Sanitizers,...,Beds/Cots,Body Bags,Lab Kit,Ventilators,Personnel,Sample Collecting Kits,Lab Platform,Bedding Accessories,Fit Testing Supplies,old week number
0,Kern,2020-06-10 to 2020-06-16,1,1656500.0,2282000.0,3673500.0,2143190.0,1161000.0,3658718.0,5707127.0,...,0.0,0.0,0.0,0.0,539.0,0.0,0.0,0.0,0.0,0.0
1,Mariposa,2020-06-10 to 2020-06-16,1,840.0,568000.0,0.0,11592.0,0.0,1680.0,32928.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Merced,2020-06-10 to 2020-06-16,1,63480.0,2894000.0,19000.0,802550.0,2072000.0,246960.0,1890.0,...,0.0,2800.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Mono,2020-06-10 to 2020-06-16,1,5900.0,461000.0,20500.0,19558.0,381500.0,308420.0,30622.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Napa,2020-06-10 to 2020-06-16,1,78344.0,774000.0,612000.0,172480.0,660000.0,820628.0,1019012.0,...,0.0,0.0,0.0,0.0,0.0,36400.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,Merced,2021-03-13 to 2021-03-19,41,1356992.0,17168400.0,1587460.0,2472850.0,26877000.0,6134960.0,232310.0,...,0.0,3430.0,0.0,56.0,414.0,443100.0,0.0,0.0,14.0,3.0
170,Glenn,2021-03-13 to 2021-03-19,41,25900.0,1815800.0,147679.0,19950.0,777000.0,1743000.0,24472.0,...,0.0,0.0,0.0,0.0,0.0,1750.0,0.0,0.0,0.0,3.0
171,Plumas,2021-03-13 to 2021-03-19,41,32312.0,701400.0,121800.0,18200.0,308000.0,94920.0,25284.0,...,0.0,0.0,0.0,168.0,0.0,0.0,0.0,0.0,133.0,3.0
172,Sierra,2021-03-13 to 2021-03-19,41,3500.0,81900.0,21028.0,12040.0,116060.0,28280.0,15974.0,...,0.0,0.0,0.0,0.0,0.0,5600.0,0.0,0.0,21.0,3.0
173,Alpine,2021-03-13 to 2021-03-19,41,4900.0,57400.0,1652.0,350.0,48160.0,4760.0,7294.0,...,0.0,0.0,0.0,0.0,0.0,700.0,0.0,0.0,0.0,3.0

In [15]:
# formatting
for product in product_list:
    new_df[product] = new_df[product].astype(float)

In [16]:
# check our results
new_df

,county,week,week number,Face Shields (Disposable),Surgical Masks,Cloth Masks,Surgical or Examination Gowns,Examination Gloves,N-95 Respirators,Hand Sanitizers,...,Beds/Cots,Body Bags,Lab Kit,Ventilators,Personnel,Sample Collecting Kits,Lab Platform,Bedding Accessories,Fit Testing Supplies,old week number
0,Kern,2020-06-10 to 2020-06-16,1,1656500.0,2282000.0,3673500.0,2143190.0,1161000.0,3658718.0,5707127.0,...,0.0,0.0,0.0,0.0,539.0,0.0,0.0,0.0,0.0,0.0
1,Mariposa,2020-06-10 to 2020-06-16,1,840.0,568000.0,0.0,11592.0,0.0,1680.0,32928.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Merced,2020-06-10 to 2020-06-16,1,63480.0,2894000.0,19000.0,802550.0,2072000.0,246960.0,1890.0,...,0.0,2800.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Mono,2020-06-10 to 2020-06-16,1,5900.0,461000.0,20500.0,19558.0,381500.0,308420.0,30622.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Napa,2020-06-10 to 2020-06-16,1,78344.0,774000.0,612000.0,172480.0,660000.0,820628.0,1019012.0,...,0.0,0.0,0.0,0.0,0.0,36400.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,Merced,2021-03-13 to 2021-03-19,41,1356992.0,17168400.0,1587460.0,2472850.0,26877000.0,6134960.0,232310.0,...,0.0,3430.0,0.0,56.0,414.0,443100.0,0.0,0.0,14.0,3.0
170,Glenn,2021-03-13 to 2021-03-19,41,25900.0,1815800.0,147679.0,19950.0,777000.0,1743000.0,24472.0,...,0.0,0.0,0.0,0.0,0.0,1750.0,0.0,0.0,0.0,3.0
171,Plumas,2021-03-13 to 2021-03-19,41,32312.0,701400.0,121800.0,18200.0,308000.0,94920.0,25284.0,...,0.0,0.0,0.0,168.0,0.0,0.0,0.0,0.0,133.0,3.0
172,Sierra,2021-03-13 to 2021-03-19,41,3500.0,81900.0,21028.0,12040.0,116060.0,28280.0,15974.0,...,0.0,0.0,0.0,0.0,0.0,5600.0,0.0,0.0,21.0,3.0
173,Alpine,2021-03-13 to 2021-03-19,41,4900.0,57400.0,1652.0,350.0,48160.0,4760.0,7294.0,...,0.0,0.0,0.0,0.0,0.0,700.0,0.0,0.0,0.0,3.0

In [17]:
# use .to_dict and 'records' orient to make our desired list
list_d = new_df.to_dict(orient='records')

In [18]:
# write to a text file for our data.js later
with open("weekly_dict.txt", "w") as file:
    file.write(json.dumps(list_d))

In [25]:
# create dataframe of weeks and week numbers, using groupby method
week_group = new_df.groupby(["week"])
weeks = week_group["week number"].unique()
group_df = pd.DataFrame({"week number": weeks})

# reset index, and cleanup for []
group_df.reset_index(inplace=True)
group_df["week number"] = group_df["week number"].str[0]
group_df

                        week  week number
0   2020-06-10 to 2020-06-16            1
1   2020-06-17 to 2020-06-23            2
2   2020-06-24 to 2020-06-30            3
3   2020-07-01 to 2020-07-07            4
4   2020-07-08 to 2020-07-14            5
5   2020-07-15 to 2020-07-21            6
6   2020-07-22 to 2020-07-28            7
7   2020-07-29 to 2020-08-04            8
8   2020-08-05 to 2020-08-14            9
9   2020-08-15 to 2020-08-21           10
10  2020-08-22 to 2020-08-28           11
11  2020-08-29 to 2020-09-04           12
12  2020-09-05 to 2020-09-11           13
13  2020-09-12 to 2020-09-18           14
14  2020-09-19 to 2020-09-25           15
15  2020-09-26 to 2020-10-02           16
16  2020-10-03 to 2020-10-09           17
17  2020-10-10 to 2020-10-16           18
18  2020-10-17 to 2020-10-23           19
19  2020-10-24 to 2020-10-30           20
20  2020-10-31 to 2020-11-06           21
21  2020-11-07 to 2020-11-13           22
22  2020-11-14 to 2020-11-20           23
23  2020-11-21 to 2020-11-27           24
24  2020-11-28 to 2020-12-04           25
25  2020-12-05 to 2020-12-11           27
26  2020-12-12 to 2020-12-18           28
27  2020-12-19 to 2020-12-25           29
28  2020-12-26 to 2021-01-01           30
29  2021-01-02 to 2021-01-08           31
30  2021-01-09 to 2021-01-15           32
31  2021-01-16 to 2021-01-22           33
32  2021-01-23 to 2021-01-29           34
33  2021-01-30 to 2021-02-05           35
34  2021-02-06 to 2021-02-12           36
35  2021-02-13 to 2021-02-19           37
36  2021-02-20 to 2021-02-26           38
37  2021-02-27 to 2021-03-05           39
38  2021-03-06 to 2021-03-12           40
39  2021-03-13 to 2021-03-19           41

In [26]:
# export week information to a separate TXT file
list_d = group_df.to_dict(orient='records')
with open("week_data.txt", "w") as file:
    file.write(json.dumps(list_d))